name: Release DroolMissle

on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x' # SDK Version to use.          
        env:
          NUGET_AUTH_TOKEN: ${{secrets.NUGET}}
      - run: dotnet build --configuration Release DroolMissle/DroolMissle.Core/DroolMissle.Core.csproj
      - name: Create the package
        run: dotnet pack --configuration Release DroolMissle/DroolMissle.Core/DroolMissle.Core.csproj
      - name: Publish the package to GPR
        run: dotnet nuget push DroolMissle/DroolMissle.Core/DroolMissle.Core.csproj/bin/Release/*.nupkg
